### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Review by DaFlowah — CHANGES_REQUESTED** [review]
There are many errors.
Somewhere you took off the articles, somewhere you put it.
Somewhere "zip" is written in CAPS LOCK, somewhere else no.
"Pò" instead of "po'" is a bad grammar mistake.
And "occultamento" is more for dead bodies.
In lines 118 and 131 you forgot the capital letter.

**Comment by bovirus** [comment]
What for you is an error for me could be not error.
Are your sure that the previous one was better and right?

For me not always is necessary the article
In many strings is not necessary (when are menus or options) and could be more important when it's a full description.

ZIP should be always in uppercase when you talk about file type. 
Is not in uppercase when you type about file extension ex ".zip" or somethings like that

Ok for "po'" (Accademia della Crusca say that is right....)

The action of to hide action in Italian has not a real sound like fine term.
But "Occultamento" is surely more "elegant" than original one "Nascondendo" that is not Italian in this context.

In original translation there are some strings with wrong grammatical person ("Concede" should be "Concedi", etc)

The terms between () normally didn't start in uppercase (is not a new phrase)

"Scarica" for "Download" is not always right. "Download" is more known.

**Comment by auanasgheps** [comment]
_Occultamento_ is a terrible translation.

Others are welcome, like _Pulisci cache_ to _Svuota cache_ or _ZIP_ are good findings. However:

- You changed ZIP only once as said by @DaFlowah - but left _zip_ in other strings. You can't leave it as this.
- Original strings file, which is the one you should use for reference, uses _zip_ and **not** _ZIP_ 

_Scarica_ is perfectly fine.  In Italian we say "Vuoi scaricare questo file".

You changed _È disponibile Magisk v%1$s!_ to _È disponibile Magisk v. %1$s_, but the original does not have any dot (_Magisk v%1$s is available!_). Again, you should use the original file as reference.
I don't understand why you changed _Completa disinstallazione_ to _Disisntalalzione completa_, you even **mispelled** it.

> Are your sure that the previous one was better and right?

Damn yes.

Either way I will revert most of these _less obvious_ changes you made.
Fixing and keeping updated this work is time consuming, please avoid to make it worse.
Honestly I would **refuse** this pull request, there are **too many errors**.

**Comment by bovirus** [comment]
@auanasgheps 

I'm a professional translator that works for many important freeware/shareware project as officiali translator and I have years of experience in translations.

The article in many menu/option for Italian text most of time is not necessary and considering that with article Italian language is longer than Italian you can create lines with more rows or truncated lines.

For "Download" term when you use in a description like "Vuoi scaricare il file" is ok.
But when you use the terms alone a single word or ina short sentence is better "Download" then "Scarica".
And for most of the Italian users is more clear "Download" then "Scarica" (as "Upload" instead "Invia").
 
If you are Italian you cannot starting a phrase in affermative sense with "Nascondendo"?
I cam confirm that "Occultamento" is surely better than original term.
"Occultamneto" explains the concept and the action. And the terms is really Italian.
The current one "Nascondendo" is not Italian (you should say "Sto nascondendo" but in the pc message you shouldn't use reflexive person) in this context.

Also if you use in English one " v%1$" is more clear " v. %1$" (what's the problem to sue it?)

**Comment by auanasgheps** [comment]
The article in menus is fine because there is space, and allow to explains better: yours is not italian.

Nascondendo makes perfectly sense. Many people confirmed that is better than Occultamento.

You should use the original string file as reference and not change it, that's the problem with that.

If you are a professional translator, my grandmother had wheels, and she was a bike.
Your work is incomplete, misplaced, mispelled, and most corrections don't make sense at all.

**Comment by bovirus** [comment]
@auanasgheps 

Thanks for the offense (If you are a professional translator,  my grandmother had wheels, and she was a bike).

And please please take care that I didn't offense no one (as you did).

"Nascondendo ..." is not italian.  It's an Italian grammatical error.
At least you should use "Sto nascondendo..."
If someone continue to insist of "Nascondendo" is right it means that you didn't know the base of the Italian grammar.

The first translation of Magisk app was mine.
The new strings added were made in wrong way.
By someone that has no experience on translations and on software.

That's all.

If you think that is Ok for you, it's Ok for me.
But I'm not agree about translation and knowledge of Italian grammar.

**Comment by auanasgheps** [comment]
_Sto nascondendo qlc_ obviously is the full sentence. However, omitting **sto** is not an error, is just making the phrase shorter. Anyway we can make the full sentence, although I don't like it very much it's just a toast message.

> The first translation of Magisk app was mine.

Aaaaah, thank you for this confirmation! That's why there were so many errors, and I had to redo almost everything! 
You abandoned this project in september and I took over, so thanks for some useful corrections (we are all humans, I'm not saying I don't make mistakes). However I will keep stressing that my translation is much better, also because some Magisk users have given feedback to me.

PS: I translate apps and programs since years, and my mother is an actual translator who taught many things. For example:

- Always use reference material. In this field, Microsoft Language portal is a perfect fit.
- Try to provide best clarity, if space allows. That's why I prefer to use articles where possible
- Always double-check (proof-reading) your translation. I actually translate with spell checker enabled, that's why my translations never have spelling issues.

I'm just saying here that I'm not somebody who has no experience on software (consultant at VMware) nor translations.

**Comment by erikholmes564** [comment]
Honestly I think that @auanasgheps and @daflowah are right.
I just want to point out that the use of the gerundive alone is allowed only in the rarest of the cases (for example in titles or when it is used as a noun).
Moreover I would not use "occultamento" instead of "nascondendo".
In fact, even if it is correct to say that "occultare" is used in the meaning of conceal something I hear it more often in the crime beat than in other circumstances.
Said such things, this pull request should be refused.

Edit: It wasn't clear but I wanted to say that I prefer "nascondendo" rather than "sto nascondendo" or "occultamento".

**Comment by bovirus** [comment]
@auanasgheps 

You said that others made the errors.
is not acceptable for you that you made the errors.

The original (not mine) translation contains in some points errors the seems to explain missing knowledge of Italian base grammar (ex. Nascondendo).

For me as translator is not not important if I or others likes the translations.
As translator for me it's important that I use a clear and "right" Italian translation and terms.

Please check the software databases of Microsoft and Adobe (should be a reference for all translators about sofwtare program).
No one use "nascondendo" nor other gerundive mode.
No one use in menu/option the article very often.

"Pulisci cache" is not Italian (the right one is "Svuota cache")

(System default) is "(predefinito sistema)" and not "(Predefinito)".
The terms between () should be always in lower case (not new paragraph)

Some string in original translation  use the some structure as original English, but in Italian we revert the structure.

If you like please use continue to use this wrong (by grammar point of view) translation (that as you said seems that likes to many users).

I will use mine. Because I cannot be agree with that.

@IgnisReinhard 

Please take that the point in a translation is not what "we like" or "we don't like"
The point if it's Italian or not

**Comment by auanasgheps** [comment]
> You said that others made the errors.
is not acceptable for you that you made the errors.

You probably haven't read what I wrote before: _we are all humans, I'm not saying I don't make mistakes_

> The original (not mine) translation contains in some points errors the seems to explain missing knowledge of Italian base grammar (ex. Nascondendo).

Like @IgnisReinhard said, it can be used. 2-1 for _Nascondendo_ team, sorry

> No one use in menu/option the article very often.

This is partially true because you removed useful articles in too many strings.

> "Pulisci cache" is not Italian (the right one is "Svuota cache")

You are right here. As I said earlier, some of your changes are welcome, but are just a little part.

> (System default) is "(predefinito sistema)" and not "(Predefinito)".
> The terms between () should be always in lower case (not new paragraph)

It's upper case in the original file, so I will use upper case.

**Comment by topjohnwu** [comment]
Um... so any agreements yet?

**Comment by bovirus** [comment]
@auanasgheps 

You said some times that the original one was in some way and you follow it.
You shouldn't follow the rules of original files about grammar that it's English when you translate it in Italian.
English grammar use different rules of Italian grammar. Ex:
In Italian grammar only first word in a phrase it's in uppercase (except own name).
In Italian grammar the sense of complex phrase many times is flipped than original English one.
In Italian grammar the terms between () are always starting in lower case (is not a new paragraph).

As I said we are not discussing if "Nascondendo" could be likely or not (could be agree with you) .
"Nascondendo" as start of a phrase is not Italian.
The right gerundive mode in Italian is "Sto nascondendo".
As I wrote in software most of the program didn't use gerundive mode.
 
The translation of "system default" is not only "predefinito" but "predefinito sistema" (different meaning).

As I said I'm not interested to continue the discussion.
I already explained my point of view about Italian grammar.

Thanks.

**Comment by auanasgheps** [comment]
@topjohnwu Definitely not. This pull request is too controversial and contains too many mistakes, shared by other users as well.

**Comment by bovirus** [comment]
@auanasgheps

I agree with you that tit' too controversial.

But please didn't insist about that your "terms" are likely by others users.
For me the right point is not if the terms are likely or not, but instead if it's grammatically right.
Italian grammar is not like a Facebook group (where you use like o don't like).
Please take care that no one make a controversial about the rule of Italian grammar. because the rules are clear and fixed.
For me is not important if others users likely your original translation.
For me as translator it's important if a translation contains terms that follow the rules of Italian grammar and the strings are clear and right in the phrase context.
I posted the technical point of view because on some terms I'm not agree about current translation.

@topjohnwu 

For me the current translation is not right in some point (that i explained with details).
In some terms it's seems just a word by word translation from English (that not following Italian grammar).

As I explained  I'm not interested to continue the discussion because it seems that the important point here is if the translation is likely (please check the posts) or not and not (as I believe) if it's grammatically right (that is my point of view).

Please cancel my pull-up request. 

Thanks.

**Comment by topjohnwu** [comment]
Closed as requested.

**Pull request closed without merging**
