### PR TITLE
Added Dutch translation! <3

### PR DESCRIPTION
**Pull request by Naamloos**
nl stands for Netherlands
Happy #hacktoberfest!

### CODE REVIEW

**Comment by Naamloos** [comment]
I noticed I forgot some strings, Will add commit with More translate strings later

**Comment by Naamloos** [comment]
Dutch translation is complete now.

**Comment by topjohnwu** [comment]
Thanks a lot!!

**Comment by Naamloos** [comment]
No problem, glad I could help

**Pull request merged**
