### PR TITLE
german: fix typos and translate new strings

### PR DESCRIPTION
**Pull request by drbeat**

### CODE REVIEW

**Comment by c727** [comment]
line 26: both forms are possible, shorter version is more common imo. From which state do you come from? http://www.duden.de/rechtschreibung/neu
line 47: ^
line 49: OK - new string
line 50: OK - new string
line 91: no way, grammer
line 132: OK - plural is correct here

**Comment by c727** [comment]
btw you could add fixes for these strings to your commit:
screenshot_2017-02-06-15-24-20
screenshot_2017-02-06-15-24-34

my device has 720p...

**Comment by drbeat** [comment]
line 26: both forms are correct yet the longer is more common
line 47: ^
line 91: it's "der Speicher" therefore it is "auf dem Speicher"

**Comment by c727** [comment]
26 & 47: OK let's change it to "neueste"...

91: https://de.wiktionary.org/wiki/Speicher & https://de.wikipedia.org/wiki/Akkusativ
it's "den Speicher"...

Maybe we can change this string to something similar like in AOSP because not all devices have an external storage:
speicheraosp

**Pull request merged**
