### PR TITLE
Updated russian translation

### PR DESCRIPTION
**Pull request by alice-mkh**
I've shortened target_uid, grant and fab_flash_zip (which is now unused btw) lines because they were too long to fit in the UI previously.

### CODE REVIEW

**Comment by alice-mkh** [comment]
Also, I cannot translate "Core only mode" in any good way. I've looked into other translations and they seem to translate it as either 'Only "core mode"' as if there are many modes including "core" one, or '"Core Only" mode' as if "Core Only" is a name.

**Comment by RoySchutte** [comment]
[PLEASE CORRECT ME IF I'M WRONG]

I think you should interpret "Core Only" as a name, because it's a state (mode) of Magisk.

Two modes of Magisk:
- Full mode (default - not mentioned in translations)
- Core Only mode (only core features enabled)

'Only "core mode"' makes no sense to me.

**Comment by alice-mkh** [comment]
I agree with you, but the problem is that you can't really translate such a name. I've left it untranslated (as "Режим Core Only"), but it's pretty much meaningless when translated this way. Even if I translate it literally, I'll have to at least add quotes, and it'll still be meaningless.

And I agree that 'Only "core mode"' makes no sense at all.

**Comment by alice-mkh** [comment]
Example: Polish translation. "Tylko Tryb Rdzeni" == "Only Mode of Cores", from what I understand.

**Comment by RoySchutte** [comment]
You could try to find another word (synonym) for 'core' that works for your language. The description will explain the meaning.

e.g.
Essentials only mode
Main functions only mode
Fundamentals only mode

Good luck.

**Comment by alice-mkh** [comment]
Is "Basic mode" or "Restricted mode" ok?

**Comment by RoySchutte** [comment]
I wouldn't call it restricted. But 'Basic mode' I, as a user, would understand. If the description is clear.

**Comment by alice-mkh** [comment]
Done.

**Pull request merged**
