### PR TITLE
Updated Italian language

### PR DESCRIPTION
**Pull request by bovirus**
Please update Italian language.: Thanks.

### CODE REVIEW

**Review by TheComputerGuy96 — CHANGES_REQUESTED** [review]
Lines 4-6 should be removed

**Comment by bovirus** [comment]
@TheComputerGuy96

I left the two strings in Italian to check the text string lines alignment with master English language.
The additional string (4-6) untranmlasted (are the original names of the app) didn't create any problem.

**Comment by TheComputerGuy96** [comment]
@bovirus See this commit: https://github.com/topjohnwu/MagiskManager/commit/aac088d4962c0e3d5b8d3e1e17a3fb5702002fbf

**Comment by bovirus** [comment]
@TheComputerGuy96 

I check in the commit but i just see NL/RO changes.

**Comment by TheComputerGuy96** [comment]
@bovirus Remove these lines: https://github.com/bovirus/MagiskManager/blob/5f4b58e507dbf487cc148fa14efaf5f15b46c3a0/app/src/main/res/values-it/strings.xml#L2-L6

**Pull request merged**
