### PR TITLE
[F-Droid] Killing play-services dependency in a newly created flavor

### PR DESCRIPTION
**Pull request by thermatk**
One step closer to F-Droid inclusion, other items being:
- [ ] Clear license (#172, #174)
- [ ] Prebuilt libbusybox should be built on compile time, but on [xda you shared that ](https://forum.xda-developers.com/showpost.php?p=72293984&postcount=20)
> No More Busybox!

so this might not even be needed.

### CODE REVIEW

**Comment by topjohnwu** [comment]
Building busybox along with the application seems nearly impossible.
Busybox requires its own building environment and settings, not sure how I am able to support that

**Comment by thermatk** [comment]
I'm not sure about busybox/libbusybox, but it's certainly possible

here is an app which uses ordinary busybox prebuilts for ordinary releases, but builds compile-time for f-droid:
https://github.com/meefik/busybox
and here is the metadata showing how it builds
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/ru.meefik.busybox.txt

**Comment by TheComputerGuy96** [comment]
@thermatk Magisk no longer needs busybox

**Comment by thermatk** [comment]
libbusybox binaries are there with no *.mk to rebuild them

**Comment by topjohnwu** [comment]
I have spent some time dealing with this issue.
Finally, the main app is now 100% FOSS!
Check this: 42a6e0dd10943392707bd6fcd7dab22b6561a29b

**Comment by dimqua** [comment]
@topjohnwu do you allow to add the app to the F-Droid? They can't do it without your permission. ;-)

**Pull request closed without merging**
